### PR TITLE
Modification to ease inclusion in jWeather project

### PR DESCRIPTION
**Pull request by clinique**
Hello,
I would like to submit some small modifications that would allow the usage of com.nwpi.synop in right in the jWeather project (https://github.com/arimus/jweather) that already handles METAR and TAF messages.

### CODE REVIEW

**Comment by Jonarzz** [comment]
I am sorry, I was not on GitHub for some time. I appreciate your input! Merged your changes of course. Thank you!

**Comment by clinique** [comment]
Hello, again !
Nearly two years later. I made an integration of your work into a home automation project called Openhab (see pull request [here](https://github.com/openhab/openhab2-addons/pull/1573#pullrequestreview-35754577)). 
But this project is EPL based license and Treeware is a bit exotic for such project. Would you agree double licensing your code ?

Thanks a lot.
BR

**Comment by Jonarzz** [comment]
Hi there!
Sure thing, you can use my code however you want as long as you mention me as the author or partial contributor (basically MIT in this case, I think it will be all right?). I'm really glad you made use of my work!
Best regards,
Jonarzz

**Comment by clinique** [comment]
Thanks for your validation. Of course you're mentionned as contributor (see readme file [here](https://github.com/clinique/openhab2-addons/blob/SynopAnalyzer/addons/binding/org.openhab.binding.synopanalyzer/about.html).
Openhab is very cautious regarding license (part of the project is Eclipse based). Thus would you be kind enough to modify your README.md file to mention Eclipse Public License as an alternative license for SynopAnalizer ?

Thanks  a lot.

**Comment by Jonarzz** [comment]
Added the line to the README file. If it should look differently, contact me, please. Always happy to help :)

Best regards,
Jonarzz

**Comment by clinique** [comment]
Great, thanks a lot Jonarzz.
Best regards
Gaël

**Pull request merged**
